[phases.setup]
nixPkgs = [
  "glib",
  "nss",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "expat",
  "fontconfig",
  "freetype",
  "libdrm",
  "libxkbcommon",
  "mesa",
  "alsa-lib",
  "pango",
  "cairo"
]